//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMenu
    {
        public SMenu()
        {
            this.FControlMenus = new HashSet<FControlMenu>();
        }
    
        public System.Guid Guid { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.Guid> GuidLanguage { get; set; }
        public Nullable<int> OrderMenu { get; set; }
        public string Icon { get; set; }
        public Nullable<System.Guid> GuidParent { get; set; }
        public string Type { get; set; }
        public string LinkUrl { get; set; }
        public string FriendUrl { get; set; }
        public string RouterUrl { get; set; }
    
        public virtual ICollection<FControlMenu> FControlMenus { get; set; }
    }
}
